package com.azizyilmaz.common.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;

public record TransferRequest(@NotBlank(message = "firmAccountId cannot be empty.") String firmAccountId,
                              @NotBlank(message = "customerAccountId cannot be empty.") String customerAccountId,
                              @NotNull(message = "amount cannot be empty.") @DecimalMin(value = "0.01", message = "amount must be at least 0.01.") BigDecimal amount,
                              @NotBlank(message = "correlationId is mandatory — idempotency key") String correlationId
                              // idempotency (generated by firm)
) {
}
